name: Java CI with Gradle

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: Windows-latest

    env:
      # optional (defaults to `postgres`)
      PGDB: opls
      # required
      POSTGRES_PASSWORD: postgres
      # optional (defaults to `postgres`)
      POSTGRES_USER: oplsusr

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Start PostgreSQL on Windows
      run: |
        $pgService = Get-Service -Name postgresql*
        Set-Service -InputObject $pgService -Status running -StartupType automatic
        Start-Process -FilePath "$env:PGBIN\pg_isready" -Wait -PassThru
    - name: Create oplsusr user on Windows
      run: |
        & $env:PGBIN\psql --command="CREATE USER $env:POSTGRES_USER PASSWORD '$env:POSTGRES_PASSWORD' SUPERUSER CREATEDB" --command="\du"
    - name: Create opls database
      run: |
        & $env:PGBIN\createdb --owner=$env:POSTGRES_USER $env:PGDB
        $env:PGPASSWORD=$env:POSTGRES_PASSWORD
        & $env:PGBIN\psql --username=$env:POSTGRES_USER --host=localhost --list $env:PGDB

    - name: Execute Gradle build
      run: |
        cd opls-backend && ./gradlew clean build
